# ==========================================
# CodeMagic CI/CD Configuration
# MakaNetu - Risk Place Angola
# ==========================================
# 
# Workflows:
# - android-develop: Build de teste (Firebase App Distribution)
# - android-production: Build de produção (Google Play Store)
#
# Environment Management:
# - develop branch → Test builds → Firebase App Distribution
# - main branch → Production builds → Google Play Store (Internal Testing)
# ==========================================

workflows:
  # ==========================================
  # WORKFLOW: ANDROID DEVELOP (TESTES)
  # ==========================================
  android-develop:
    name: Android Develop - Test Build
    
    max_build_duration: 60
    
    instance_type: mac_mini_m1
    
    environment:
      groups:
        # Grupo de variáveis para desenvolvimento
        - develop_environment
      
      vars:
        # Configurações do Flutter
        FLUTTER_VERSION: "3.35.7"
        
        # Configurações do Android
        PACKAGE_NAME: "ao.riskplace.makanetu"
        
        # Configurações do Firebase
        FIREBASE_APP_ID_ANDROID: $FIREBASE_APP_ID_ANDROID_DEV
        FIREBASE_TOKEN: $FIREBASE_CLI_TOKEN
        
        # Build configurations
        BUILD_TYPE: "debug"
        
      flutter: stable
      
      xcode: latest
      
      cocoapods: default
    
    triggering:
      events:
        - push
        - pull_request
      
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
      
      cancel_previous_builds: true
    
    scripts:
      - name: 🔧 Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: 🔍 Analyze code
        script: |
          flutter analyze
      
      - name: 🧪 Run tests
        script: |
          flutter test
        ignore_failure: true
      
      - name: 📝 Setup Firebase configuration
        script: |
          # Copiar arquivo de configuração do Firebase para development
          if [ -f "android/app/google-services-dev.json" ]; then
            cp android/app/google-services-dev.json android/app/google-services.json
          fi
      
      - name: 🏗️ Build Android APK (Debug)
        script: |
          flutter build apk --debug --flavor development
      
      - name: 🚀 Upload to Firebase App Distribution
        script: |
          echo "Installing Firebase CLI..."
          npm install -g firebase-tools
          
          echo "Deploying to Firebase App Distribution..."
          firebase appdistribution:distribute \
            build/app/outputs/flutter-apk/app-development-debug.apk \
            --app $FIREBASE_APP_ID_ANDROID_DEV \
            --groups "testers" \
            --release-notes "Build automático da branch develop - $(date)" \
            --token $FIREBASE_CLI_TOKEN
    
    artifacts:
      - build/app/outputs/**/*.apk
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/mapping.txt
      - flutter_drive.log
    
    publishing:
      email:
        recipients:
          - $TEAM_EMAIL
        notify:
          success: true
          failure: true
      
      slack:
        channel: '#ci-cd-notifications'
        notify_on_build_start: true
        notify:
          success: true
          failure: true

  # ==========================================
  # WORKFLOW: ANDROID PRODUCTION (GOOGLE PLAY)
  # ==========================================
  android-production:
    name: Android Production - Google Play Release
    
    max_build_duration: 90
    
    instance_type: mac_mini_m1
    
    environment:
      groups:
        # Grupo de variáveis para produção
        - production_environment
        - google_play_credentials
      
      vars:
        # Configurações do Flutter
        FLUTTER_VERSION: "3.35.7"
        
        # Configurações do Android
        PACKAGE_NAME: "ao.riskplace.makanetu"
        
        # Build configurations
        BUILD_TYPE: "release"
        
        # Google Play configurations
        GOOGLE_PLAY_TRACK: "internal"
        
      android_signing:
        - makaneto_keystore
      
      flutter: stable
      
      xcode: latest
      
      cocoapods: default
    
    triggering:
      events:
        - push
        - tag
      
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'release/*'
          include: true
          source: true
      
      cancel_previous_builds: false
    
    scripts:
      - name: 🔧 Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: 🔍 Analyze code
        script: |
          flutter analyze
        ignore_failure: false
      
      - name: 🧪 Run tests (Production)
        script: |
          flutter test
        ignore_failure: false
      
      - name: 📝 Setup Firebase configuration (Production)
        script: |
          # Copiar arquivo de configuração do Firebase para produção
          if [ -f "android/app/google-services-prod.json" ]; then
            cp android/app/google-services-prod.json android/app/google-services.json
          fi
      
      - name: 🔢 Update version code
        script: |
          # Incrementar automaticamente o version code
          VERSION_NAME=$(grep 'version:' pubspec.yaml | sed 's/version: //' | cut -d'+' -f1)
          VERSION_CODE=$(($(grep 'version:' pubspec.yaml | sed 's/version: //' | cut -d'+' -f2) + 1))
          
          echo "Building version $VERSION_NAME+$VERSION_CODE"
          
          # Atualizar pubspec.yaml
          sed -i '' "s/version: .*/version: $VERSION_NAME+$VERSION_CODE/" pubspec.yaml
      
      - name: 🏗️ Build Android App Bundle (Release)
        script: |
          flutter build appbundle \
            --release \
            --build-name=$VERSION_NAME \
            --build-number=$VERSION_CODE
      
      - name: 🚀 Publish to Google Play (Internal Testing)
        script: |
          echo "Publishing to Google Play Store - Internal Testing Track"
          
          # CodeMagic automaticamente publica usando as credenciais configuradas
          # A publicação é feita via Google Play Console API
    
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/mapping.txt
      - build/app/outputs/**/output-metadata.json
    
    publishing:
      # Publicação no Google Play Store
      google_play:
        credentials: $GCLOUD_SERVICE_ACCOUNT_CREDENTIALS
        track: $GOOGLE_PLAY_TRACK
        submit_as_draft: false
        rollout_fraction: 0.1
        changes_not_sent_for_review: false
        in_app_update_priority: 3
      
      email:
        recipients:
          - $TEAM_EMAIL
          - $PRODUCT_OWNER_EMAIL
        notify:
          success: true
          failure: true
      
      slack:
        channel: '#releases'
        notify_on_build_start: true
        notify:
          success: true
          failure: true
      
      # Notificações adicionais
      scripts:
        - name: 🎉 Send release notification
          script: |
            echo "✅ Nova versão $VERSION_NAME+$VERSION_CODE publicada no Google Play Store!"
            echo "Track: Internal Testing"
            echo "Rollout: 10% dos usuários"

  # ==========================================
  # WORKFLOW: ANDROID STAGING (OPCIONAL)
  # ==========================================
  android-staging:
    name: Android Staging - Pre-Production Test
    
    max_build_duration: 60
    
    instance_type: mac_mini_m1
    
    environment:
      groups:
        - staging_environment
      
      vars:
        FLUTTER_VERSION: "3.35.7"
        PACKAGE_NAME: "ao.riskplace.makanetu"
        BUILD_TYPE: "release"
      
      android_signing:
        - makaneto_keystore
      
      flutter: stable
    
    triggering:
      events:
        - push
      
      branch_patterns:
        - pattern: 'staging'
          include: true
          source: true
        - pattern: 'release/*'
          include: true
          source: true
      
      cancel_previous_builds: true
    
    scripts:
      - name: 🔧 Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: 🔍 Analyze code
        script: |
          flutter analyze
      
      - name: 🧪 Run tests
        script: |
          flutter test
      
      - name: 🏗️ Build Android App Bundle (Staging)
        script: |
          flutter build appbundle --release --flavor staging
      
      - name: 🚀 Deploy to Firebase App Distribution (Staging Group)
        script: |
          npm install -g firebase-tools
          firebase appdistribution:distribute \
            build/app/outputs/bundle/stagingRelease/app-staging-release.aab \
            --app $FIREBASE_APP_ID_ANDROID_STAGING \
            --groups "staging-testers" \
            --release-notes "Build de staging - Pre-production test" \
            --token $FIREBASE_CLI_TOKEN
    
    artifacts:
      - build/app/outputs/**/*.aab
      - build/app/outputs/**/mapping.txt
    
    publishing:
      email:
        recipients:
          - $TEAM_EMAIL
        notify:
          success: true
          failure: true

  # ==========================================
  # WORKFLOW: iOS DEVELOP (TESTFLIGHT BETA)
  # ==========================================
  ios-develop:
    name: iOS Develop - TestFlight Beta
    
    max_build_duration: 60
    
    instance_type: mac_mini_m1
    
    environment:
      groups:
        - ios_develop_environment
        - app_store_credentials
      
      vars:
        FLUTTER_VERSION: "3.35.7"
        BUNDLE_ID: "ao.riskplace.makanetu"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        
      flutter: stable
      
      xcode: latest
      
      cocoapods: default
      
      ios_signing:
        distribution_type: app_store
        bundle_identifier: ao.riskplace.makanetu
    
    triggering:
      events:
        - push
        - pull_request
      
      branch_patterns:
        - pattern: 'develop'
          include: true
          source: true
      
      cancel_previous_builds: true
    
    scripts:
      - name: 🔧 Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: 🍎 Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      
      - name: 🔍 Analyze code
        script: |
          flutter analyze
      
      - name: 🧪 Run tests
        script: |
          flutter test
        ignore_failure: true
      
      - name: 📝 Setup Firebase configuration (Development)
        script: |
          # Copiar arquivo de configuração do Firebase para development
          if [ -f "ios/Runner/GoogleService-Info-dev.plist" ]; then
            cp ios/Runner/GoogleService-Info-dev.plist ios/Runner/GoogleService-Info.plist
          fi
      
      - name: 🏗️ Build iOS IPA (Development)
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=ios/ExportOptions.plist \
            --build-name=1.0.0 \
            --build-number=$BUILD_NUMBER
      
      - name: 🚀 Publish to TestFlight
        script: |
          echo "Publishing to TestFlight Beta..."
          # CodeMagic automaticamente publica usando App Store Connect API
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - flutter_drive.log
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
          - Beta Testers
        
        submit_to_app_store: false
      
      email:
        recipients:
          - $TEAM_EMAIL
        notify:
          success: true
          failure: true
      
      slack:
        channel: '#ci-cd-notifications'
        notify_on_build_start: true
        notify:
          success: true
          failure: true

  # ==========================================
  # WORKFLOW: iOS PRODUCTION (APP STORE)
  # ==========================================
  ios-production:
    name: iOS Production - App Store Release
    
    max_build_duration: 90
    
    instance_type: mac_mini_m1
    
    environment:
      groups:
        - ios_production_environment
        - app_store_credentials
      
      vars:
        FLUTTER_VERSION: "3.35.7"
        BUNDLE_ID: "ao.riskplace.makanetu"
        XCODE_WORKSPACE: "Runner.xcworkspace"
        XCODE_SCHEME: "Runner"
        
      flutter: stable
      
      xcode: latest
      
      cocoapods: default
      
      ios_signing:
        distribution_type: app_store
        bundle_identifier: ao.riskplace.makanetu
    
    triggering:
      events:
        - push
        - tag
      
      branch_patterns:
        - pattern: 'main'
          include: true
          source: true
        - pattern: 'release/*'
          include: true
          source: true
      
      cancel_previous_builds: false
    
    scripts:
      - name: 🔧 Get Flutter packages
        script: |
          flutter packages pub get
      
      - name: 🍎 Install CocoaPods dependencies
        script: |
          cd ios
          pod install
      
      - name: 🔍 Analyze code
        script: |
          flutter analyze
        ignore_failure: false
      
      - name: 🧪 Run tests (Production)
        script: |
          flutter test
        ignore_failure: false
      
      - name: 📝 Setup Firebase configuration (Production)
        script: |
          # Copiar arquivo de configuração do Firebase para produção
          if [ -f "ios/Runner/GoogleService-Info-prod.plist" ]; then
            cp ios/Runner/GoogleService-Info-prod.plist ios/Runner/GoogleService-Info.plist
          fi
      
      - name: 🔢 Update version code
        script: |
          # Incrementar automaticamente o version code
          VERSION_NAME=$(grep 'version:' pubspec.yaml | sed 's/version: //' | cut -d'+' -f1)
          VERSION_CODE=$(($(grep 'version:' pubspec.yaml | sed 's/version: //' | cut -d'+' -f2) + 1))
          
          echo "Building version $VERSION_NAME+$VERSION_CODE"
          
          # Atualizar pubspec.yaml
          sed -i '' "s/version: .*/version: $VERSION_NAME+$VERSION_CODE/" pubspec.yaml
      
      - name: 🏗️ Build iOS IPA (Production)
        script: |
          flutter build ipa \
            --release \
            --export-options-plist=ios/ExportOptions.plist \
            --build-name=$VERSION_NAME \
            --build-number=$VERSION_CODE
      
      - name: 🚀 Publish to App Store
        script: |
          echo "Publishing to App Store..."
          # CodeMagic automaticamente publica usando App Store Connect API
    
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - ios/**/GeneratedPluginRegistrant.m
    
    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_IDENTIFIER
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID
        
        # Primeiro vai para TestFlight
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
        
        # Depois submete para review da App Store
        submit_to_app_store: true
        
        release_type: MANUAL
        
        # Informações para App Store
        copyright: "2025 Risk Place Angola"
        
      email:
        recipients:
          - $TEAM_EMAIL
          - $PRODUCT_OWNER_EMAIL
        notify:
          success: true
          failure: true
      
      slack:
        channel: '#releases'
        notify_on_build_start: true
        notify:
          success: true
          failure: true
