// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVh-zkFgR6ZSOZeAZ7K26A1a0aPKP_xT0',
    appId: '1:982759520741:android:77d4bd1fe13bdafd91d70c',
    messagingSenderId: '982759520741',
    projectId: 'riskplace-ao',
    databaseURL: 'https://riskplace-ao-default-rtdb.firebaseio.com',
    storageBucket: 'riskplace-ao.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyHbRLd89tq1QCpLjLxQpKQmizDQHvy4w',
    appId: '1:982759520741:ios:c11f3fbb13d55b8d91d70c',
    messagingSenderId: '982759520741',
    projectId: 'riskplace-ao',
    databaseURL: 'https://riskplace-ao-default-rtdb.firebaseio.com',
    storageBucket: 'riskplace-ao.firebasestorage.app',
    iosBundleId: 'ao.riskplace.makanetu',
  );
}
