// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAVh-zkFgR6ZSOZeAZ7K26A1a0aPKP_xT0',
    appId: '1:982759520741:android:ad9b3684e031923691d70c',
    messagingSenderId: '982759520741',
    projectId: 'riskplace-ao',
    storageBucket: 'riskplace-ao.firebasestorage.app',
    databaseURL: 'https://riskplace-ao-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAyHbRLd89tq1QCpLjLxQpKQmizDQHvy4w',
    appId: '1:982759520741:ios:01306662a59be32091d70c',
    messagingSenderId: '982759520741',
    projectId: 'riskplace-ao',
    storageBucket: 'riskplace-ao.firebasestorage.app',
    iosBundleId: 'ao.riskplace.maka',
    databaseURL: 'https://riskplace-ao-default-rtdb.firebaseio.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCh8CEWp9E4IaZAj-CcN52DikvgaCx_VBc',
    appId: '1:982759520741:web:e3a77efb2fadd71691d70c',
    messagingSenderId: '982759520741',
    projectId: 'riskplace-ao',
    authDomain: 'riskplace-ao.firebaseapp.com',
    storageBucket: 'riskplace-ao.firebasestorage.app',
    measurementId: 'G-4NNYDPLXDT',
    databaseURL: 'https://riskplace-ao-default-rtdb.firebaseio.com',
  );

}